-- The overall application status table
create table if not exists EVEREST_STATUS (
    ID integer not null PRIMARY KEY,
    SCHEMA_VERSION integer
);

insert into 
    EVEREST_STATUS ( id, schema_version ) 
    values    (  1,              1 );

create table if not exists FORUM_TOPIC (
    ID integer not null AUTO_INCREMENT PRIMARY KEY,
    TYPE varchar(32),
    SEASON integer,
    RACE integer,
    URL varchar(256)
);

CREATE TABLE if not exists CAR
(
   ID integer NOT NULL AUTO_INCREMENT PRIMARY KEY ,
   POWER integer,
   HANDLING integer,
   ACCELERATION integer,
   BRAKES_PARTID integer,
   CHASSIS_PARTID integer,
   COOLING_PARTID integer,
   ELECTRONICS_PARTID integer,
   ENGINE_PARTID integer,
   FRONT_WING_PARTID integer,
   GEARBOX_PARTID integer,
   REAR_WING_PARTID integer,
   SIDEPODS_PARTID integer,
   SUSPENSION_PARTID integer,
   UNDERBODY_PARTID integer
);

CREATE TABLE if not exists CAR_PART
(
   ID integer NOT NULL AUTO_INCREMENT PRIMARY KEY ,
   LEVEL integer,
   NAME varchar(32),
   WEAR decimal(19,5)
);

CREATE TABLE if not exists CAR_SETTINGS
(
   ID integer NOT NULL AUTO_INCREMENT PRIMARY KEY,
   BRAKES integer,
   ENGINE integer,
   FRONT_WING integer,
   GEAR integer,
   REAR_WING integer,
   SUSPENSION integer,
   TYRE varchar(32)
);

CREATE TABLE if not exists DRIVER
(
   ID integer NOT NULL AUTO_INCREMENT PRIMARY KEY,
   NUMBER integer,
   AGE integer,
   AGGRESSIVENESS integer,
   CHARISMA integer,
   CONCENTRATION integer,
   EXPERIENCE integer,
   MOTIVATION integer,
   OVERALL integer,
   REPUTATION integer,
   STAMINA integer,
   TALENT integer,
   TECH_INSIGHT integer,
   WEIGHT integer,
   NAME varchar(255)
);

CREATE TABLE if not exists FAVORITE_TRACK
(
   DRIVER_ID integer NOT NULL,
   TRACK_ID integer NOT NULL,
   CONSTRAINT CONSTRAINT_6 PRIMARY KEY (DRIVER_ID,TRACK_ID)
);

CREATE TABLE if not exists LAP
(
   ID integer NOT NULL AUTO_INCREMENT PRIMARY KEY,
   NUMBER integer,
   TIME integer,
   POSITION integer,
   TYRE varchar(32),
   WEATHER varchar(32),
   TEMPERATURE integer,
   HUMIDITY integer,
   EVENTS varchar(255)
);

CREATE TABLE if not exists STINT
(
   ID integer NOT NULL AUTO_INCREMENT PRIMARY KEY,
   RACE_ID integer NOT NULL,
   NUMBER integer,
   INITIAL_LAP integer,
   FINAL_LAP integer,
   REASON varchar(64),
   TYRE varchar(32),
   TYRE_LEFT integer,
   TYRE_USED decimal(19,5),
   TYRE_NO_BAD decimal(19,5),
   TYRE_DURABILITY decimal(19,5),
   AVG_TEMP decimal(19,5),
   AVG_HUM decimal(19,5),
   FUEL_START decimal(19,5),
   FUEL_LEFT decimal(19,5),
   REFUELED_TO integer,
   PIT_TIME integer
);

CREATE TABLE if not exists RACE
(
   ID integer NOT NULL AUTO_INCREMENT PRIMARY KEY,
   SEASON_NUMBER integer,
   RACE_NUMBER integer,
   MANAGER_NAME varchar(64),
   GROUP_NAME varchar(32),
   TRACK_ID integer,
   RACE_STATUS varchar(32),
   TYRE_SUPPLIER varchar(32), 
   RACE_SETTINGS_ID integer,
   RISK_CLEAR integer,
   RISK_DEFEND integer,
   RISK_MALFUNCTION integer,
   RISK_OVERTAKE integer,
   DRIVER_START_ID integer,
   DRIVER_FINISH_ID integer,
   TD_STATUS varchar(32),
   TD_ID integer,
   CAR_START_ID integer,
   CAR_FINISH_ID integer,
   CAR_WEAR_ID integer,
   FUEL_START integer,
   FUEL_FINISH integer,
   FUEL_USED decimal(19,5),
   AVG_TEMP decimal(19,5),
   AVG_HUM decimal(19,5),
   DISTANCE decimal(19,5),
   TOOL varchar(32),
   URL varchar(256)
);

CREATE TABLE if not exists RACE_LAP
(
   RACE_ID integer NOT NULL,
   LAP_ID integer NOT NULL,
   CONSTRAINT CONSTRAINT_2AE PRIMARY KEY (RACE_ID,LAP_ID)
);

CREATE TABLE if not exists TECH_DIRECTOR
(
   ID integer NOT NULL AUTO_INCREMENT PRIMARY KEY,
   NUMBER integer,
   NAME varchar(32),
   OVERALL integer,
   LEADERSHIP integer,
   RD_MECH integer,
   RD_ELECT integer,
   RD_AERO integer,
   EXPERIENCE integer,
   PIT_COORD integer,
   MOTIVATION integer,
   AGE integer
);

CREATE TABLE if not exists TRACK
(
   ID integer PRIMARY KEY NOT NULL,
   NAME varchar(255),
   POWER integer,
   HANDLING integer,
   ACCELERATION integer,
   AVG_SPEED double,
   CORNERS integer,
   DISTANCE double,
   LAP_DISTANCE double,
   LAPS integer,
   TIME_IN_OUT integer,
   DOWNFORCE varchar(32),
   FUEL_CONSUMPTION varchar(32),
   GRIP_LEVEL varchar(32),
   OVERTAKING varchar(32),
   SUSPENSION varchar(32),
   TYRE_WEAR varchar(32),
   BRAKESWF decimal(19,5),
   CHASSISWF decimal(19,5),
   COOLINGWF decimal(19,5),
   ELECTRONICSWF decimal(19,5),
   ENGINEWF decimal(19,5),
   FRONT_WINGWF decimal(19,5),
   GEARBOXWF decimal(19,5),
   REAR_WINGWF decimal(19,5),
   SIDEPODSWF decimal(19,5),
   SUSPENSIONWF decimal(19,5),
   UNDERBODYWF decimal(19,5),
   FUEL_COEF decimal(19,9),
   COMPOUND_COEF decimal(19,9),
   SETUP_WINGS integer,
   SETUP_ENGINE integer,
   SETUP_BRAKES integer,
   SETUP_GEAR integer,
   SETUP_SUSPENSION integer,
   WING_SPLIT integer,
   WING_NORMAL boolean,
   F_CON integer,
   F_AGR integer,
   F_EXP integer,
   F_TEI integer,
   F_ENG integer,
   F_ELE integer,
   F_HUM decimal(19,5),
   F_FUE decimal(19,5)
);

CREATE TABLE if not exists TYRE_SUPPLIER
(
   ID integer NOT NULL AUTO_INCREMENT PRIMARY KEY,
   SEASON_NUMBER integer,
   NAME varchar(32),
   DRY integer,
   WET integer,
   PEAK integer,
   DURABILITY integer,
   WARMUP integer,
   COST integer
);

ALTER TABLE CAR
ADD CONSTRAINT FK107B48C3403AB
FOREIGN KEY (CHASSIS_PARTID)
REFERENCES CAR_PART(ID);

ALTER TABLE CAR
ADD CONSTRAINT FK107B435D3BE14
FOREIGN KEY (SUSPENSION_PARTID)
REFERENCES CAR_PART(ID);

ALTER TABLE CAR
ADD CONSTRAINT FK107B4FB5D5B35
FOREIGN KEY (GEARBOX_PARTID)
REFERENCES CAR_PART(ID);

ALTER TABLE CAR
ADD CONSTRAINT FK107B4E728FE78
FOREIGN KEY (COOLING_PARTID)
REFERENCES CAR_PART(ID);

ALTER TABLE CAR
ADD CONSTRAINT FK107B4AF71AF3A
FOREIGN KEY (ELECTRONICS_PARTID)
REFERENCES CAR_PART(ID);

ALTER TABLE CAR
ADD CONSTRAINT FK107B4B3B708E9
FOREIGN KEY (BRAKES_PARTID)
REFERENCES CAR_PART(ID);

ALTER TABLE CAR
ADD CONSTRAINT FK107B42487EC4C
FOREIGN KEY (SIDEPODS_PARTID)
REFERENCES CAR_PART(ID);

ALTER TABLE CAR
ADD CONSTRAINT FK107B47D5A480F
FOREIGN KEY (ENGINE_PARTID)
REFERENCES CAR_PART(ID);

ALTER TABLE CAR
ADD CONSTRAINT FK107B420582602
FOREIGN KEY (REAR_WING_PARTID)
REFERENCES CAR_PART(ID);

ALTER TABLE CAR
ADD CONSTRAINT FK107B4FF2B0C5D
FOREIGN KEY (FRONT_WING_PARTID)
REFERENCES CAR_PART(ID);

ALTER TABLE CAR
ADD CONSTRAINT FK107B4AEE202D7
FOREIGN KEY (UNDERBODY_PARTID)
REFERENCES CAR_PART(ID);

ALTER TABLE FAVORITE_TRACK
ADD CONSTRAINT FK8372DB0CB0000
FOREIGN KEY (DRIVER_ID)
REFERENCES DRIVER(ID);

ALTER TABLE FAVORITE_TRACK
ADD CONSTRAINT FK8372DFE7D1111
FOREIGN KEY (TRACK_ID)
REFERENCES TRACK(ID);

ALTER TABLE STINT
ADD CONSTRAINT FK8472DFE7DF46E
FOREIGN KEY (RACE_ID)
REFERENCES RACE(ID);

ALTER TABLE RACE
ADD CONSTRAINT FK26BEF1B6E317D
FOREIGN KEY (CAR_START_ID)
REFERENCES CAR(ID);

ALTER TABLE RACE
ADD CONSTRAINT FK26BEF1E2815284
FOREIGN KEY (CAR_FINISH_ID)
REFERENCES CAR(ID);

ALTER TABLE RACE
ADD CONSTRAINT FK26BEF163528284
FOREIGN KEY (CAR_WEAR_ID)
REFERENCES CAR(ID);

ALTER TABLE RACE
ADD CONSTRAINT FK26BEF1E0321C89
FOREIGN KEY (RACE_SETTINGS_ID)
REFERENCES CAR_SETTINGS(ID);

ALTER TABLE RACE
ADD CONSTRAINT FK26BEF157C76D17
FOREIGN KEY (DRIVER_START_ID)
REFERENCES DRIVER(ID);

ALTER TABLE RACE
ADD CONSTRAINT FK26BEF1E00EC4CE
FOREIGN KEY (TRACK_ID)
REFERENCES TRACK(ID);

ALTER TABLE RACE
ADD CONSTRAINT FK26BEF157C76333
FOREIGN KEY (DRIVER_FINISH_ID)
REFERENCES DRIVER(ID);

CREATE INDEX SEASON_RACE_INDEX ON RACE(SEASON_NUMBER,RACE_NUMBER);
CREATE INDEX MANAGER_INDEX ON RACE(MANAGER_NAME);
CREATE INDEX SUPPLIER_INDEX ON RACE(TYRE_SUPPLIER);

ALTER TABLE RACE_LAP
ADD CONSTRAINT FK8372DFE7DF46E
FOREIGN KEY (RACE_ID)
REFERENCES RACE(ID);

ALTER TABLE RACE_LAP
ADD CONSTRAINT FK8372DB0CB9B49
FOREIGN KEY (LAP_ID)
REFERENCES LAP(ID);

CREATE INDEX SEASON_SUPPLIER_INDEX ON TYRE_SUPPLIER(SEASON_NUMBER,NAME);

CREATE INDEX FORUM_TOPIC_INDEX ON FORUM_TOPIC(TYPE,SEASON,RACE);



