ALTER TABLE STINT
  ADD COLUMN( WEATHER_TYPE varchar(16) );

ALTER TABLE RACE
ADD CONSTRAINT FK26BEF187436D17
FOREIGN KEY (TD_ID)
REFERENCES TECH_DIRECTOR(ID);

update EVEREST_STATUS
    set schema_version = 2
    where id = 1;



