/*
 * This java source file is generated by DAO4J v1.18
 * Generated on Fri Jan 04 19:21:50 EST 2013
 * For more information, please contact b-i-d@163.com
 * Please check http://members.lycos.co.uk/dao4j/ for the latest version.
 */

package org.gproman.db.model.orm;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import org.gproman.db.DBUtil;
import org.gproman.db.model.dao.DriverDAO;
import org.gproman.db.model.dao.FavoriteTrackDAO;
import org.gproman.db.model.dao.IdGeneratorDAO;
import org.gproman.model.driver.Driver;
import org.gproman.model.track.Track;

/**
 * This class provides methods to populate DB Table of DRIVER
 */
public class DriverDAOImpl
        implements
        DriverDAO {

    public static final DriverDAO INSTANCE   = new DriverDAOImpl();

    /* SQL to insert data */
    private static final String   SQL_INSERT =
                                                     "INSERT INTO DRIVER ("
                                                             + "ID, NUMBER, DATETIME, AGE, AGGRESSIVENESS, CHARISMA, CONCENTRATION, EXPERIENCE, MOTIVATION, "
                                                             + "OVERALL, REPUTATION, STAMINA, TALENT, TECH_INSIGHT, WEIGHT, CONTRACT, "
                                                             + "FASTEST_LAPS, GPS, NAME, NATIONALITY, PODIUMS, POINTS, POLES, "
                                                             + "SALARY, TROPHIES, WINS"
                                                             + ") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

    /* SQL to select data */
    private static final String   SQL_SELECT =
                                                     "SELECT "
                                                             + "ID, NUMBER, DATETIME, AGE, AGGRESSIVENESS, CHARISMA, CONCENTRATION, EXPERIENCE, MOTIVATION, "
                                                             + "OVERALL, REPUTATION, STAMINA, TALENT, TECH_INSIGHT, WEIGHT, CONTRACT, "
                                                             + "FASTEST_LAPS, GPS, NAME, NATIONALITY, PODIUMS, POINTS, POLES, "
                                                             + "SALARY, TROPHIES, WINS "
                                                             + "FROM DRIVER WHERE "
                                                             + "ID = ?";

    /* SQL to update data */
    private static final String   SQL_UPDATE =
                                                     "UPDATE DRIVER SET "
                                                             + "NUMBER = ?, DATETIME = ?, AGE = ?, AGGRESSIVENESS = ?, CHARISMA = ?, CONCENTRATION = ?, EXPERIENCE = ?, MOTIVATION = ?, OVERALL = ?,  "
                                                             + "REPUTATION = ?, STAMINA = ?, TALENT = ?, TECH_INSIGHT = ?, WEIGHT = ?, CONTRACT = ?, FASTEST_LAPS = ?,  "
                                                             + "GPS = ?, NAME = ?, NATIONALITY = ?, PODIUMS = ?, POINTS = ?, POLES = ?, SALARY = ?,  "
                                                             + "TROPHIES = ?, WINS = ? "
                                                             + "WHERE "
                                                             + "ID = ?";

    /* SQL to delete data */
    private static final String   SQL_DELETE =
                                                     "DELETE FROM DRIVER WHERE "
                                                             + "ID = ?";

    private FavoriteTrackDAO      ftDAO      = FavoriteTrackDAOImpl.INSTANCE;

    private DriverDAOImpl() {
    }

    /**
     * Create a new record in Database.
     * @param driver   The Object to be inserted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void create(Driver driver,
                       Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            driver.setId( IdGeneratorDAO.INSTANCE.getNextId( conn ) );
            int index = 1;
            ps = conn.prepareStatement( SQL_INSERT );
            ps.setInt( index++, driver.getId() );
            ps.setInt( index++, driver.getNumber() );
            ps.setTimestamp( index++, driver.getDatetime() );
            ps.setInt( index++, driver.getAttributes().getAge() );
            ps.setInt( index++, driver.getAttributes().getAggressiveness() );
            ps.setInt( index++, driver.getAttributes().getCharisma() );
            ps.setInt( index++, driver.getAttributes().getConcentration() );
            ps.setInt( index++, driver.getAttributes().getExperience() );
            ps.setInt( index++, driver.getAttributes().getMotivation() );
            ps.setInt( index++, driver.getAttributes().getOverall() );
            ps.setInt( index++, driver.getAttributes().getReputation() );
            ps.setInt( index++, driver.getAttributes().getStamina() );
            ps.setInt( index++, driver.getAttributes().getTalent() );
            ps.setInt( index++, driver.getAttributes().getTechInsight() );
            ps.setInt( index++, driver.getAttributes().getWeight() );
            ps.setInt( index++, driver.getContract() );
            ps.setInt( index++, driver.getFastestLaps() );
            ps.setInt( index++, driver.getGps() );
            ps.setString( index++, driver.getName() );
            ps.setString( index++, driver.getNationality() );
            ps.setInt( index++, driver.getPodiums() );
            ps.setInt( index++, driver.getPoints() );
            ps.setInt( index++, driver.getPoles() );
            ps.setInt( index++, driver.getSalary() );
            ps.setInt( index++, driver.getTrophies() );
            ps.setInt( index++, driver.getWins() );
            ps.executeUpdate();

            for ( Track track : driver.getFavoriteTracks() ) {
                ftDAO.create( driver.getId(), track.getId(), conn );
            }
        } finally {
            close( ps );
        }
    }

    /**
     * Retrive a record from Database.
     * @param beanKey   The PK Object to be retrived.
     * @param conn      JDBC Connection.
     * @exception       SQLException if something is wrong.
     */
    public Driver load(Integer key,
                       Connection conn) throws SQLException {
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            ps = conn.prepareStatement( SQL_SELECT );
            ps.setInt( 1, key );
            rs = ps.executeQuery();
            List<Driver> results = getResults( rs, conn );
            if ( results.size() > 0 ) return (Driver) results.get( 0 );
            else return null;
        } finally {
            close( rs );
            close( ps );
        }
    }

    /**
     * Update a record in Database.
     * @param bean   The Object to be saved.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public int update(Driver bean,
                      Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            Driver saved = load( bean.getId(), conn );
            int result = 0;
            if ( saved != null ) {

                ps = conn.prepareStatement( SQL_UPDATE );
                int index = 1;
                ps.setInt( index++, bean.getNumber() );
                ps.setTimestamp( index++, bean.getDatetime() );
                ps.setInt( index++, bean.getAttributes().getAge() );
                ps.setInt( index++, bean.getAttributes().getAggressiveness() );
                ps.setInt( index++, bean.getAttributes().getCharisma() );
                ps.setInt( index++, bean.getAttributes().getConcentration() );
                ps.setInt( index++, bean.getAttributes().getExperience() );
                ps.setInt( index++, bean.getAttributes().getMotivation() );
                ps.setInt( index++, bean.getAttributes().getOverall() );
                ps.setInt( index++, bean.getAttributes().getReputation() );
                ps.setInt( index++, bean.getAttributes().getStamina() );
                ps.setInt( index++, bean.getAttributes().getTalent() );
                ps.setInt( index++, bean.getAttributes().getTechInsight() );
                ps.setInt( index++, bean.getAttributes().getWeight() );
                ps.setInt( index++, bean.getContract() );
                ps.setInt( index++, bean.getFastestLaps() );
                ps.setInt( index++, bean.getGps() );
                ps.setString( index++, bean.getName() );
                ps.setString( index++, bean.getNationality() );
                ps.setInt( index++, bean.getPodiums() );
                ps.setInt( index++, bean.getPoints() );
                ps.setInt( index++, bean.getPoles() );
                ps.setInt( index++, bean.getSalary() );
                ps.setInt( index++, bean.getTrophies() );
                ps.setInt( index++, bean.getWins() );
                ps.setInt( index++, bean.getId() );
                result = ps.executeUpdate();

                List<Track> stracks = saved.getFavoriteTracks();

                for ( int i = 0; i < bean.getFavoriteTracks().size(); i++ ) {
                    Track newTrack = bean.getFavoriteTracks().get( i );
                    if ( i < stracks.size() ) {
                        Track strack = stracks.get( i );
                        if ( !strack.equals( newTrack ) ) {
                            ftDAO.delete( bean.getId(), strack.getId(), conn );
                            ftDAO.create( bean.getId(), newTrack.getId(), conn );
                        }
                    } else {
                        ftDAO.create( bean.getId(), newTrack.getId(), conn );
                    }
                }
                for ( int i = bean.getFavoriteTracks().size(); i < stracks.size(); i++ ) {
                    Track track = stracks.get( i );
                    ftDAO.delete( bean.getId(), track.getId(), conn );
                }
            }

            return result;
        } finally {
            close( ps );
        }
    }

    /**
     * Create a new record in Database.
     * @param bean   The PK Object to be deleted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void delete(Integer key,
                       Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            Driver driver = load( key, conn );
            for ( Track track : driver.getFavoriteTracks() ) {
                ftDAO.delete( driver.getId(), track.getId(), conn );
            }

            ps = conn.prepareStatement( SQL_DELETE );
            ps.setInt( 1, key );
            ps.executeUpdate();
        } finally {
            close( ps );
        }
    }

    /**
     * Populate the ResultSet.
     * @param rs     The ResultSet.
     * @return       The Object to retrieve from DB.
     * @exception    SQLException if something is wrong.
     */
    private List<Driver> getResults(ResultSet rs,
                                    Connection conn) throws SQLException {
        List<Driver> results = new ArrayList<Driver>();
        while ( rs.next() ) {
            Driver bean = new Driver();
            bean.setId( rs.getInt( "ID" ) );
            bean.setDatetime( rs.getTimestamp( "DATETIME" ) );
            bean.setNumber( rs.getInt( "NUMBER" ) );
            bean.getAttributes().setAge( DBUtil.getIntOrNull( rs, "AGE" ) );
            bean.getAttributes().setAggressiveness( DBUtil.getIntOrNull( rs, "AGGRESSIVENESS" ) );
            bean.getAttributes().setCharisma( DBUtil.getIntOrNull( rs, "CHARISMA" ) );
            bean.getAttributes().setConcentration( DBUtil.getIntOrNull( rs, "CONCENTRATION" ) );
            bean.getAttributes().setExperience( DBUtil.getIntOrNull( rs, "EXPERIENCE" ) );
            bean.getAttributes().setMotivation( DBUtil.getIntOrNull( rs, "MOTIVATION" ) );
            bean.getAttributes().setOverall( DBUtil.getIntOrNull( rs, "OVERALL" ) );
            bean.getAttributes().setReputation( DBUtil.getIntOrNull( rs, "REPUTATION" ) );
            bean.getAttributes().setStamina( DBUtil.getIntOrNull( rs, "STAMINA" ) );
            bean.getAttributes().setTalent( DBUtil.getIntOrNull( rs, "TALENT" ) );
            bean.getAttributes().setTechInsight( DBUtil.getIntOrNull( rs, "TECH_INSIGHT" ) );
            bean.getAttributes().setWeight( DBUtil.getIntOrNull( rs, "WEIGHT" ) );
            bean.setContract( DBUtil.getIntOrNull( rs, "CONTRACT" ) );
            bean.setFastestLaps( DBUtil.getIntOrNull( rs, "FASTEST_LAPS" ) );
            bean.setGps( DBUtil.getIntOrNull( rs, "GPS" ) );
            bean.setName( rs.getString( "NAME" ) );
            bean.setNationality( rs.getString( "NATIONALITY" ) );
            bean.setPodiums( DBUtil.getIntOrNull( rs, "PODIUMS" ) );
            bean.setPoints( DBUtil.getIntOrNull( rs, "POINTS" ) );
            bean.setPoles( DBUtil.getIntOrNull( rs, "POLES" ) );
            bean.setSalary( DBUtil.getIntOrNull( rs, "SALARY" ) );
            bean.setTrophies( DBUtil.getIntOrNull( rs, "TROPHIES" ) );
            bean.setWins( DBUtil.getIntOrNull( rs, "WINS" ) );

            List<Track> tracks = ftDAO.loadFavoriteTracks( bean.getId(), conn );
            bean.setFavoriteTracks( tracks );

            results.add( bean );
        }
        return results;
    }

    /**
     * Close JDBC Statement.
     * @param stmt  Statement to be closed.
     */
    private void close(Statement stmt) {
        if ( stmt != null ) {
            try {
                stmt.close();
            } catch ( SQLException e ) {
            }
        }
    }

    /**
     * Close JDBC ResultSet.
     * @param rs  ResultSet to be closed.
     */
    private void close(ResultSet rs) {
        if ( rs != null ) {
            try {
                rs.close();
            } catch ( SQLException e ) {
            }
        }
    }
}