/*
 * This java source file is generated by DAO4J v1.18
 * Generated on Fri Jan 04 19:21:50 EST 2013
 * For more information, please contact b-i-d@163.com
 * Please check http://members.lycos.co.uk/dao4j/ for the latest version.
 */

package org.gproman.db.model.orm;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import org.gproman.db.model.dao.IdGeneratorDAO;
import org.gproman.db.model.dao.PartOptionDAO;
import org.gproman.model.car.PartOption;

/**
 * This class provides methods to populate DB Table of PART_OPTION
 */
public class PartOptionDAOImpl implements PartOptionDAO {
    
    public static final PartOptionDAO INSTANCE = new PartOptionDAOImpl();
    
    /* SQL to insert data */
    private static final String SQL_INSERT =
        "INSERT INTO PART_OPTION ("
        + "ID, PART_ID, ACTION, COST, NEW_WEAR, TO_LEVEL"
        + ") VALUES (?, ?, ?, ?, ?, ?)";

    /* SQL to select data */
    private static final String SQL_SELECT =
        "SELECT "
        + "ID, PART_ID, ACTION, COST, NEW_WEAR, TO_LEVEL "
        + "FROM PART_OPTION WHERE "
        + "ID = ?";

    private static final String SQL_SELECT_FOR_PART =
            "SELECT "
            + "ID, PART_ID, ACTION, COST, NEW_WEAR, TO_LEVEL "
            + "FROM PART_OPTION WHERE "
            + "PART_ID = ?";

    /* SQL to update data */
    private static final String SQL_UPDATE =
        "UPDATE PART_OPTION SET "
        + "PART_ID = ?, ACTION = ?, COST = ?, NEW_WEAR = ?, TO_LEVEL = ? "
        + "WHERE "
        + "ID = ?";

    /* SQL to delete data */
    private static final String SQL_DELETE =
        "DELETE FROM PART_OPTION WHERE "
        + "ID = ?";

    private PartOptionDAOImpl() {}
    
    /**
     * Create a new record in Database.
     * @param bean   The Object to be inserted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void create(Integer partId, PartOption bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            bean.setId( IdGeneratorDAO.INSTANCE.getNextId( conn ) );
            ps = conn.prepareStatement(SQL_INSERT);
            ps.setInt(1, bean.getId());
            ps.setInt(2, partId);
            ps.setString(3, bean.getAction().toString());
            ps.setInt(4, bean.getCost());
            ps.setDouble(5, bean.getNewWear());
            ps.setInt(6, bean.getToLevel());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Retrive a record from Database.
     * @param beanKey   The PK Object to be retrived.
     * @param conn      JDBC Connection.
     * @exception       SQLException if something is wrong.
     */
    public PartOption load(Integer key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            ps = conn.prepareStatement(SQL_SELECT);
            ps.setInt(1, key);
            rs = ps.executeQuery();
            List<PartOption> results = getResults(rs);
            if (results.size() > 0)
                return (PartOption) results.get(0);
            else
                return null;
        }finally {
            close(rs);
            close(ps);
        }
    }

    public List<PartOption> loadOptionsForPart(Integer partId, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            ps = conn.prepareStatement(SQL_SELECT_FOR_PART);
            ps.setInt(1, partId);
            rs = ps.executeQuery();
            List<PartOption> results = getResults(rs);
            return results;
        } finally {
            close(rs);
            close(ps);
        }
    }

    /**
     * Update a record in Database.
     * @param bean   The Object to be saved.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public int update(Integer partId, PartOption bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_UPDATE);
            ps.setInt(1, partId);
            ps.setString(2, bean.getAction().toString() );
            ps.setInt(3, bean.getCost());
            ps.setDouble(4, bean.getNewWear());
            ps.setInt(5, bean.getToLevel());
            ps.setInt(6, bean.getId());
            return ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Create a new record in Database.
     * @param bean   The PK Object to be deleted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void delete(Integer key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_DELETE);
            ps.setInt(1, key);
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }
    
    /**
     * Populate the ResultSet.
     * @param rs     The ResultSet.
     * @return       The Object to retrieve from DB.
     * @exception    SQLException if something is wrong.
     */
    private List<PartOption> getResults(ResultSet rs) throws SQLException {
        List<PartOption> results = new ArrayList<PartOption>();
        while (rs.next()) {
            PartOption bean = new PartOption();
            bean.setId(rs.getInt("ID"));
            String ac = rs.getString("ACTION");
            bean.setAction( ac != null ? PartOption.Action.valueOf( ac ) : null );
            bean.setCost(rs.getInt("COST"));
            bean.setNewWear(rs.getDouble("NEW_WEAR"));
            bean.setToLevel(rs.getInt("TO_LEVEL"));
            results.add(bean);
        }
        return results;
    }

    /**
     * Close JDBC Statement.
     * @param stmt  Statement to be closed.
     */
    private void close(Statement stmt) {
        if (stmt != null) {
            try {
                stmt.close();
            }catch(SQLException e){}
        }
    }

    /**
     * Close JDBC ResultSet.
     * @param rs  ResultSet to be closed.
     */
    private void close(ResultSet rs) {
        if (rs != null) {
            try {
                rs.close();
            }catch(SQLException e){}
        }
    }
}