/*
 * This java source file is generated by DAO4J v1.18
 * Generated on Fri Jan 04 19:21:50 EST 2013
 * For more information, please contact b-i-d@163.com
 * Please check http://members.lycos.co.uk/dao4j/ for the latest version.
 */

package org.gproman.db.model.orm;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import org.gproman.db.model.dao.IdGeneratorDAO;
import org.gproman.db.model.dao.LapDAO;
import org.gproman.db.model.dao.QualifyDAO;
import org.gproman.model.race.Qualify;

/**
 * This class provides methods to populate DB Table of QUALIFY
 */
public class QualifyDAOImpl implements QualifyDAO {
    
    public static final QualifyDAO INSTANCE = new QualifyDAOImpl();
    
    /* SQL to insert data */
    private static final String SQL_INSERT =
        "INSERT INTO QUALIFY ("
        + "ID, NUMBER, RISK_DESCR, LAP_ID"
        + ") VALUES (?, ?, ?, ?)";

    /* SQL to select data */
    private static final String SQL_SELECT =
        "SELECT "
        + "ID, NUMBER, RISK_DESCR, LAP_ID "
        + "FROM QUALIFY WHERE "
        + "ID = ?";

    /* SQL to update data */
    private static final String SQL_UPDATE =
        "UPDATE QUALIFY SET "
        + "NUMBER = ?, RISK_DESCR = ?, LAP_ID = ? "
        + "WHERE "
        + "ID = ?";

    /* SQL to delete data */
    private static final String SQL_DELETE =
        "DELETE FROM QUALIFY WHERE "
        + "ID = ?";
    
    private LapDAO lapDAO = LapDAOImpl.INSTANCE;
    
    private QualifyDAOImpl() {}

    /**
     * Create a new record in Database.
     * @param bean   The Object to be inserted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void create(Qualify bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            lapDAO.create( bean.getLap(), conn );
            bean.setId( IdGeneratorDAO.INSTANCE.getNextId( conn ) );
            ps = conn.prepareStatement(SQL_INSERT);
            ps.setInt(1, bean.getId());
            ps.setInt(2, bean.getNumber());
            ps.setString(3, bean.getRiskDescr());
            ps.setInt(4, bean.getLap().getId());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Retrive a record from Database.
     * @param beanKey   The PK Object to be retrived.
     * @param conn      JDBC Connection.
     * @exception       SQLException if something is wrong.
     */
    public Qualify load(Integer key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            ps = conn.prepareStatement(SQL_SELECT);
            ps.setInt(1, key);
            rs = ps.executeQuery();
            List<Qualify> results = getResults(rs, conn);
            if (results.size() > 0)
                return results.get(0);
            else
                return null;
        }finally {
            close(rs);
            close(ps);
        }
    }

    /**
     * Update a record in Database.
     * @param bean   The Object to be saved.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void update(Qualify bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_UPDATE);
            ps.setInt(1, bean.getNumber());
            ps.setString(2, bean.getRiskDescr());
            ps.setInt(3, bean.getLap().getId());
            ps.setInt(4, bean.getId());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Create a new record in Database.
     * @param bean   The PK Object to be deleted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void delete(Integer key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            Qualify qualify = load( key, conn );
            ps = conn.prepareStatement(SQL_DELETE);
            ps.setInt(1, key);
            ps.executeUpdate();
            lapDAO.delete( qualify.getLap().getId(), conn );
        }finally {
            close(ps);
        }
    }
    
    /**
     * Populate the ResultSet.
     * @param rs     The ResultSet.
     * @return       The Object to retrieve from DB.
     * @exception    SQLException if something is wrong.
     */
    private List<Qualify> getResults(ResultSet rs, Connection conn ) throws SQLException {
        List<Qualify> results = new ArrayList<Qualify>();
        while (rs.next()) {
            Qualify bean = new Qualify();
            bean.setId(rs.getInt("ID"));
            bean.setNumber(rs.getInt("NUMBER"));
            bean.setRiskDescr(rs.getString("RISK_DESCR"));
            bean.setLap( lapDAO.load( rs.getInt("LAP_ID"), conn ) );
            results.add(bean);
        }
        return results;
    }

    /**
     * Close JDBC Statement.
     * @param stmt  Statement to be closed.
     */
    private void close(Statement stmt) {
        if (stmt != null) {
            try {
                stmt.close();
            }catch(SQLException e){}
        }
    }

    /**
     * Close JDBC ResultSet.
     * @param rs  ResultSet to be closed.
     */
    private void close(ResultSet rs) {
        if (rs != null) {
            try {
                rs.close();
            }catch(SQLException e){}
        }
    }
}