/*
 * This java source file is generated by DAO4J v1.18
 * Generated on Fri Jan 04 19:21:50 EST 2013
 * For more information, please contact b-i-d@163.com
 * Please check http://members.lycos.co.uk/dao4j/ for the latest version.
 */

package org.gproman.db.model.dao;

import java.sql.Connection;
import java.sql.SQLException;

import org.gproman.model.race.Forecast;

/**
 * This interface provides methods to populate DB Table of LAP
 */
public interface ForecastDAO {
    /**
     * Create a new record in Database.
     * @param forecast   The Object to be inserted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void create(Forecast forecast, Connection conn) throws SQLException;

    /**
     * Retrive a record from Database.
     * @param key       The PK Object to be retrived.
     * @param conn      JDBC Connection.
     * @exception       SQLException if something is wrong.
     */
    public Forecast load(Integer key, Connection conn) throws SQLException;

    /**
     * Update a record in Database.
     * @param forecast   The Object to be saved.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void update(Forecast bean, Connection conn) throws SQLException;

    /**
     * Delete a new record in Database.
     * @param key    The PK Object to be deleted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void delete(Integer key, Connection conn) throws SQLException;
}