/*
 * This java source file is generated by DAO4J v1.18
 * Generated on Fri Jan 04 19:21:50 EST 2013
 * For more information, please contact b-i-d@163.com
 * Please check http://members.lycos.co.uk/dao4j/ for the latest version.
 */

package org.gproman.db.model.dao;

import java.sql.Connection;
import java.sql.SQLException;

import org.gproman.db.model.orm.IdGeneratorDAOImpl;

/**
 * This interface provides methods retrieve a unique number to be used as an ID
 */
public interface IdGeneratorDAO {
    public static IdGeneratorDAO INSTANCE = new IdGeneratorDAOImpl();

    public Integer getNextId(Connection conn) throws SQLException;

}