/*
 * This java source file is generated by DAO4J v1.18
 * Generated on Fri Jan 04 19:21:51 EST 2013
 * For more information, please contact b-i-d@163.com
 * Please check http://members.lycos.co.uk/dao4j/ for the latest version.
 */

package org.gproman.db.model.dao;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

import org.gproman.model.season.Season;

/**
 * This interface provides methods to populate DB Table of SEASON
 */
public interface SeasonDAO {
    /**
     * Create a new record in Database.
     * @param bean   The Object to be inserted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void create(Season bean,
                       Connection conn) throws SQLException;

    /**
     * Retrive a record from Database.
     * @param beanKey   The PK Object to be retrived.
     * @param conn      JDBC Connection.
     * @exception       SQLException if something is wrong.
     */
    public Season load(Integer seasonId,
                       Connection conn) throws SQLException;

    /**
     * Update a record in Database.
     * @param bean   The Object to be saved.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public int update(Season bean,
                      Connection conn) throws SQLException;

    /**
     * Create a new record in Database.
     * @param bean   The PK Object to be deleted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void delete(Integer seasonId,
                       Connection conn) throws SQLException;

    public Season loadSeasonByNumber(String managerName,
                                     Integer number,
                                     Connection conn) throws SQLException;

    public void createOrUpdate(Season season,
                               Connection conn) throws SQLException;

    public List<Integer> loadSeasonsForSetup(Connection conn) throws SQLException;

    public List<Integer> loadSeasonsForTelemetry(Connection conn) throws SQLException;

    public List<Integer> loadSeasonsForTest(Connection conn) throws SQLException;

    public List<Season> loadSeasonsWithNullGroups(Connection conn) throws SQLException;
}