/*
 * This java source file is generated by DAO4J v1.18
 * Generated on Fri Jan 04 19:21:50 EST 2013
 * For more information, please contact b-i-d@163.com
 * Please check http://members.lycos.co.uk/dao4j/ for the latest version.
 */

package org.gproman.db.model.dao;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

import org.gproman.model.season.TyreSupplierAttrs;

/**
 * This interface provides methods to populate DB Table of TyreSupplier
 */
public interface TyreSupplierDAO {

    public void create(TyreSupplierAttrs bean, Connection conn) throws SQLException;

    public TyreSupplierAttrs load(Integer key, Connection conn) throws SQLException;

    public int update(TyreSupplierAttrs bean, Connection conn) throws SQLException;

    public void delete(Integer key, Connection conn) throws SQLException;

    public void createOrUpdate(TyreSupplierAttrs stint, Connection conn) throws SQLException;

    public List<TyreSupplierAttrs> loadSuppliersForSeason(Integer seasonNumber, Connection conn) throws SQLException;

    public TyreSupplierAttrs loadSupplierBySeasonNumber(Integer seasonNumber, String supplierName, Connection conn) throws SQLException;
    
}