/*
 * This java source file is generated by DAO4J v1.18
 * Generated on Fri Jan 04 19:21:51 EST 2013
 * For more information, please contact b-i-d@163.com
 * Please check http://members.lycos.co.uk/dao4j/ for the latest version.
 */

package org.gproman.db.everest.dao;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

import org.gproman.model.everest.NormalizedLap;

/**
 * This interface provides methods to populate DB Table of RACE_LAP
 */
public interface EverestRaceLapDAO {
    /**
     * Create a new record in Database.
     * @param bean   The Object to be inserted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void create(Integer raceId,
                       Integer lapId,
                       Connection conn) throws SQLException;

    /**
     * Retrieve a record from Database.
     * @param beanKey   The PK Object to be retrieved.
     * @param conn      JDBC Connection.
     * @exception       SQLException if something is wrong.
     */
    public List<NormalizedLap> loadLapsForRace(Integer raceId,
                                     Connection conn) throws SQLException;

    /**
     * Create a new record in Database.
     * @param bean   The PK Object to be deleted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void delete(Integer raceId,
                       Integer lapId,
                       Connection conn) throws SQLException;

    public void deleteLapsForRace(Integer raceId,
                                  Connection conn) throws SQLException;
}