/*
 * This java source file is generated by DAO4J v1.18
 * Generated on Fri Jan 04 19:21:50 EST 2013
 * For more information, please contact b-i-d@163.com
 * Please check http://members.lycos.co.uk/dao4j/ for the latest version.
 */

package org.gproman.db.everest.dao;

import java.sql.Connection;
import java.sql.SQLException;

import org.gproman.model.everest.ForumTopic;
import org.gproman.model.everest.ForumTopic.TopicType;

/**
 * This interface provides methods to populate DB Table of TyreSupplier
 */
public interface EverestForumTopicDAO {

    public void create(ForumTopic bean, Connection conn) throws SQLException;

    public ForumTopic load(Integer key, Connection conn) throws SQLException;

    public int update(ForumTopic bean, Connection conn) throws SQLException;

    public void delete(Integer key, Connection conn) throws SQLException;
    
    public void deleteAll( Connection conn ) throws SQLException;

    public void createOrUpdate(ForumTopic bean, Connection conn) throws SQLException;

    public ForumTopic loadTopic(TopicType type, Integer seasonNumber, Integer raceNumber, Connection conn) throws SQLException;
    
}